name: hvlov_flutter
description: HVlov-Flutter

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 5.0.0
  http: 0.13.0
  freezed_annotation: 0.14.0
  process_run: 0.12.1
  flutter_hooks: 0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 0.14.0+1
  build_runner: 1.11.5

flutter:
  uses-material-design: true
